name: Automatic Deployment with Ansible

# Executes when push the main branch
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    # my computer
    runs-on: self-hosted

    steps:
      - name: Download repository code
        uses: actions/checkout@v3

      - name: Execute Ansible Playbook
        # It's running in my host, have access to 'ansible-playbook'
        run: |
          cd ansible
          ansible-playbook -i inventory.ini site.yml